/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orcchg_openglsample_NativeInterface */

#ifndef _Included_com_orcchg_openglsample_NativeInterface
#define _Included_com_orcchg_openglsample_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orcchg_openglsample_NativeInterface
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_orcchg_openglsample_NativeInterface_init
  (JNIEnv *, jobject);

/*
 * Class:     com_orcchg_openglsample_NativeInterface
 * Method:    prepareAssets
 * Signature: (JLandroid/content/res/AssetManager;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orcchg_openglsample_NativeInterface_prepareAssets
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     com_orcchg_openglsample_NativeInterface
 * Method:    setSurface
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_orcchg_openglsample_NativeInterface_setSurface
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_orcchg_openglsample_NativeInterface
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_orcchg_openglsample_NativeInterface_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif

#include <android/native_window.h>
#include <android/native_window_jni.h>
#include "render.h"

struct NativeInterface {
  ANativeWindow* window;
  Render* render;

  NativeInterface();
  virtual ~NativeInterface();
};
